security:
    # Encodage du mot de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Gestion des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Zone de sécurité principale
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthentificationAuthenticator
            entry_point: App\Security\AppAuthentificationAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
            
            
    # Accès aux routes selon les rôles
    access_control:
        # Seul un vétérinaire peut accéder au dashboard admin
        - { path: ^/news, roles: PUBLIC_ACCESS }
        - { path: ^/admin/dashboard, roles: ROLE_VETERINAIRE }
        # Accès login pour tous
        - { path: ^/login, roles: PUBLIC_ACCESS }
        # Accès général : connecté au moins
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_VETERINAIRE }
        - { path: ^/cart, roles: ROLE_USER }
        

    role_hierarchy:
        ROLE_ADMIN: [ROLE_VETERINAIRE, ROLE_USER]
        ROLE_VETERINAIRE: [ROLE_USER]

    # Empêcher les accès anonymes sauf ceux explicitement permis
    #enable_authenticator_manager: true
